apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjNE5UUTFNRFk1TXl3aWFXRjBJam94TnpnMU5EVXdOamt6ZlEuWHlSenpjUEY2aklDS0hLOUUxWmdmQnRsM3hqamhrYjQ4NmtTNVJ3VHpkQQ==