apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjNE5UazJOVEkwTml3aWFXRjBJam94TnpnMU9UWTFNalEyZlEucy1naGJ6bWZEQXJqa2dRdlBmLWdRQnhFT2NCc2VwaTZRcTJMdlhXVTZNUQo=